# permissions for end users to view privatenetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privatenetwork-viewer-role
rules:
- apiGroups:
  - vpc.scaleway.com
  resources:
  - privatenetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vpc.scaleway.com
  resources:
  - privatenetworks/status
  verbs:
  - get
